### PR TITLE
Test case 5

### PR DESCRIPTION
**Pull request by emanuelasavi**
The code for TC5 is ready to go

### CODE REVIEW

**Comment by TedrosDC** [comment]
Every thing is good. Great job.

**Review by TedrosDC — COMMENTED** [review]
Brilliant work. expect the following minors:

I think repeation on line 32, you have already maximazied it on 19.

On the HTML page it is commented the following , can you please review line 73.

**Review by yahyaayabakan — COMMENTED** [review]
good to go

**Review by yahyaayabakan — COMMENTED** [review]
ready to merge

**Review by SedaYurdakul — APPROVED** [review]
They all looks correct. Well done!

**Review by tsulun — CHANGES_REQUESTED** [review]
mate, you should commit only ur testcase_5 class as you see in the files section you also committed some changes on your pom.xml and target folder. cos of this there is a conflict on your branch
before your commit,  adding target folder and pom.xml to your git ignore or commit without select them will solve the conflicts 
thanks

**Pull request closed without merging**
